version: '3.8'

services:
  webapp:
    image: sua-imagem-webapp
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DashBoardFiscais;User ID=sa;Password=Mudar123@;Trusted_Connection=False;TrustServerCertificate=True;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Mudar123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
